guests = ['kevin devine', 'brand new', 'straylight run', 'bright eyes']
print(guests[0].title())
print(guests[1].title())
print(guests[2].title())
print(guests[3].title())
print(f"I'm dying to see {guests[0].title()} in concert again!")
print(f"I'll probably never see {guests[1].title()} live again...")
print(f"I thought I'd seen {guests[2].title()}'s last concert back in '09.")
print(f"Seeing {guests[3].title()} live is a religious experience.")
canceled_band = guests.pop(1)
print(f"{canceled_band.title()} has been canceled.")
print(guests)
print(f"Sadly, {guests[1].title()} can't make it anymore.")
guests[1] = 'okkervil river'
print(guests)
print(f"But we're glad to announce {guests[1].title()} will be joining us from here on out.")
guests.append('the mountain goats')
print(guests)
print(f"Whoa, it looks like {guests[3].title()} will join us as well.")
guests.insert(2,'joyce manor')
print(f"Our last announcement is pop punk band {guests[2].title()}.")
print(guests)
print(f"So {guests[2].title()} has just played. Say goodbye!")
del guests[2]
print(guests)
print(f"Aaaand {guests[3].title()} has just delivered a great set.!")
tmg = 'the mountain goats'
guests.remove(tmg)
print(guests)
guests.sort()
print(guests)
guests.sort(reverse=True)
print(guests)
print(sorted(guests))
print(sorted(guests, reverse=True))
print(guests)
guests.reverse()
print(guests)
len(guests)
print(f"We still have {len(guests)} acts to perform tonight!")