guests = ['dakota', 'leena', 'carley', 'bea']
print(guests)
print(f"Hey, {guests[0].title()}! Let's have some wine and read poetry.")
print(f"Hi, {guests[1].title()}! Can you come over so we can overthink things?")
print(f"{guests[2].title()}, I don't know you very well, but I like your vibe.")
print(f"{guests[3].title()}, you're my favorite. Be my friend!")
print(f"Girls, {guests[2].title()} can't make it.")
guests[2] = 'jordan'
print(guests)
print(f"Hey, {guests[0].title()}! Let's have dinner this Saturday.")
print(f"Hi, {guests[1].title()}! I'll make you vegan food!")
print(f"{guests[2].title()}, help me stay on track during this dinner!")
print(f"{guests[3].title()}, let's help each other out!")
print(f"Hey, {guests[0].title()}, {guests[1].title()}, {guests[2].title()}, and {guests[3].title()}. I found a bigger dinner table!")
guests.insert(0, 'layna')
print(guests)
guests.insert(3, 'john')
print(guests)
guests.append('abbey')
print(guests)
print(f"Hey, {guests[0].title()}, come to dinner!")
print(f"I wonder if {guests[1].title()} is available on Saturday.")
print(f"Maybe {guests[2].title()} and Craig can join us soon.")
print(f"I'd very much like to discuss body positivity with {guests[3].title()}!")
print(f"I simply need to have a convo with {guests[4].title()} asap.")
print(f"If {guests[5].title()} joins us, I will DIE!")
print(f"I'm p. sure {guests[6].title()} would find this silly.")